#pragma once

#include <stddef.h>

typedef struct _hgbf_istream hgbf_istream_t;

// Code. Last opcode must be HLT.
typedef struct hgbf_code {
	size_t length;
	unsigned char bytes[];
} hgbf_code_t;

// Parse script from input stream and generate code.
// If error occurred, return NULL and record error message.
hgbf_code_t *hgbf_code_compile(hgbf_istream_t *script);

// Free the code generated by `hgbf_code_compile()`.
void hgbf_code_free(hgbf_code_t *code);
